SELECT
   * 
FROM
   C_MONEY_ALLOC 
WHERE
   MONEY_SOURCE_PRIMARY_KEY IN 
   (
      SELECT
         INTERNAL_NUMBER 
      FROM
         C_EXTERNAL_PAYMENT 
      WHERE
         SCREEN_BATCH_NUMBER = {Param1}
   )