SELECT
   IUSR.BATCH_RUN_NO AS "Batch Run Number",
   IUSR.OPENING_REG_DATE AS "Report Date",
   IUSR.DESTINATION_TYPE_NAME AS "Entity Type",
   IUSR.DESTINATION_ID AS "ALIS ID",
   IUSR.EXTERNAL_DESTINATION_ID AS "External ID",
   SUM(IUSR.SUSPENSE_AMOUNT) AS "Suspense Total"
FROM
   I_UNALLOCATED_SUSPENSE_REPORT IUSR 
WHERE
   1=1
   AND IUSR.DESTINATION_ID = {key}
   AND IUSR.EXTERNAL_DESTINATION_ID LIKE '{key}'
GROUP BY
   IUSR.BATCH_RUN_NO,
   IUSR.OPENING_REG_DATE,
   IUSR.DESTINATION_TYPE_NAME,
   IUSR.DESTINATION_ID,
   IUSR.EXTERNAL_DESTINATION_ID 
ORDER BY
   IUSR.BATCH_RUN_NO DESC;